server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=5s;

    # Frontend static files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API proxy to backend
    location /api/ {
        set $backend_upstream "http://backend:5000";

        # rewrite the path to avoid
        # "POST /undefined/guess HTTP/1.1" 405 559
        rewrite ^/api/(.*) /$1 break;
        
        proxy_pass $backend_upstream;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}