services:
  # --- Backend Database
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-vol:/var/lib/postgresql/data/pgdata
    #ports:
    #  "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      retries: 3
      interval: 10s
      timeout: 10s
  
  # --- Backend Flask Application
  backend-1:
    build: 
      context: .  # project root
      dockerfile: ./docker/backend.Dockerfile
    restart: unless-stopped
    environment: # from start-backend.sh
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: "postgres"
      FLASK_DB_USER: "postgres"
      FLASK_DB_NAME: "postgres"
      FLASK_DB_PASSWORD: "postgres"
      FLASK_DB_HOST: "postgres"
      FLASK_DB_PORT: "5432"
    #ports: 
    #  "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - backend-network

  backend-2:
    build: 
      context: .  # project root
      dockerfile: ./docker/backend.Dockerfile
    restart: unless-stopped
    environment: # from start-backend.sh
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: "postgres"
      FLASK_DB_USER: "postgres"
      FLASK_DB_NAME: "postgres"
      FLASK_DB_PASSWORD: "postgres"
      FLASK_DB_HOST: "postgres"
      FLASK_DB_PORT: "5432"
    #ports: 
    #  "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - backend-network
  
  # --- Frontend React + nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile # relative from context
    restart: "unless-stopped"
    ports:
      - "80:80" # port forwarding
    depends_on:
      - backend-1
      - backend-2
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - frontend-network
      - backend-network

# --- Networks
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

# --- Volumes
volumes:
  postgres-vol:
    driver: local