services:
  # --- Backend Database
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: ${DB_PORT:-5432}
    volumes:
      - postgres-vol:/var/lib/postgresql/data/pgdata
    #ports:
    #  "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      retries: 3
      interval: 10s
      timeout: 10s
  
  # --- Backend Flask Application
  backend:
    build: 
      context: .
      dockerfile: ./docker/backend.Dockerfile
    restart: always
    deploy:
      replicas: 2
    environment:
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: ${DB_TYPE:-postgres}
      FLASK_DB_USER: ${DB_USER:-postgres}
      FLASK_DB_NAME: ${DB_NAME:-postgres}
      FLASK_DB_PASSWORD: ${DB_PASSWORD:-postgres}
      FLASK_DB_HOST: ${DB_HOST:-postgres}
      FLASK_DB_PORT: ${DB_PORT:-5432}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - backend-network
  
  # --- Frontend React + nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile # relative from context
    restart: "unless-stopped"
    ports:
      - "80:80" # port forwarding
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend-network
      - backend-network

# --- Networks
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

# --- Volumes
volumes:
  postgres-vol:
    driver: local